version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_password_123
    ports: ["1433:1433"]
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_strong_password_123", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  redis:
    image: redis:7
    ports: ["6379:6379"]

  kafka:
    image: bitnami/kafka:3
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports: ["9092:9092"]

  product.api:
    build: ../src/Product.API
    environment:
      - ConnectionStrings__Default=Server=sqlserver;Database=ProductDb;User Id=sa;Password=Your_strong_password_123;TrustServerCertificate=True
      - Redis__Connection=redis:6379
    depends_on: [sqlserver, redis]
    ports: ["5001:8080"]

  inventory.api:
    build: ../src/Inventory.API
    environment:
      - ConnectionStrings__Default=Server=sqlserver;Database=InventoryDb;User Id=sa;Password=Your_strong_password_123;TrustServerCertificate=True
      - Kafka__BootstrapServers=kafka:9092
    depends_on: [sqlserver, kafka]
    ports: ["5002:8080"]

  order.api:
    build: ../src/Order.API
    environment:
      - ConnectionStrings__Default=Server=sqlserver;Database=OrderDb;User Id=sa;Password=Your_strong_password_123;TrustServerCertificate=True
      - Redis__Connection=redis:6379
      - Kafka__BootstrapServers=kafka:9092
      - Product__BaseUrl=http://product.api:8080
    depends_on: [sqlserver, kafka, redis, product.api]
    ports: ["5003:8080"]